# instantiate the UNet wrapper from torchcfm
_target_: torchcfm.models.unet.unet.UNetModelWrapper

# these match the reference CIFAR example defaults
dim: [3, 32, 32]
num_res_blocks: 2
num_channels: 128
channel_mult: [1, 2, 2, 2]
num_heads: 4
num_head_channels: 64
attention_resolutions: "16"
dropout: 0.1
use_checkpoint: false