batch_size:      128
num_workers:     4
lr:              2e-4
warmup:          5000
grad_clip:       1.0
total_steps:     400000
save_every_n_steps: 20000
log_every_n_steps: 100
ema_decay:       0.9999
parallel:        false
device:          cuda