name: test-koop
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core interpreter ---
  - python=3.9

  # --- Numerics / plotting (prefer conda builds) ---
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - numba=0.60.0
  - llvmlite=0.43.0
  - networkx=3.2.1
  - statsmodels=0.14.4
  - pillow=10.4.0
  - tqdm=4.66.5
  - pyyaml=6.0.2
  - requests=2.32.3
  - rich=13.9.4
  - h5py=3.12.1

  - anndata=0.10.9
  - scanpy=1.10.3
  - umap-learn=0.5.7

  # --- Dev / runtime tools, probably keep in a separate dev env ---
  # - jupyterlab=4.4.4
  # - ipykernel=6.29.5
  # - ipywidgets=8.1.5
  # - notebook=7.4.4

  # --- Everything conda doesn't carry, installed via pip as a second step ---
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchmetrics==1.7.1
      - torch-fidelity==0.3.0
      - torchsde==0.2.6
      - torchdiffeq==0.2.4
      - torchcde==0.2.5
      - torchdyn==1.0.6
      - torchcfm==1.0.7
      - geotorch==0.3.0
      - clean-fid==0.1.35
      - lightning==2.4.0

      - optuna==2.10.1
      - wandb==0.19.8
      - tensorboard==2.18.0
      - tbparse==0.0.9
      - pytorch-lightning==1.9.5

      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - omegaconf==2.3.0

      - opencv-python==4.11.0.86
