_target_: torchvision.datasets.CIFAR10

root: ${paths.raw_dir}
train: true
download: true

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std:  [0.5, 0.5, 0.5]