_target_: jump_wtf.data.gray_cifar.CIFARSubsetGray

root: ${paths.raw_dir}
download: true
train: true

# pick classes here, or override on the command line
classes_to_keep: ["dog"]

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5]
      std:  [0.5]
