_target_: jump_wtf.models.unet_wrapper.UNetWrapperKoopman
dim:           ${dim}
num_channels:  32
num_res_blocks: 1
# Supposed to be the exact defaults used
channel_mult: [1, 2, 2]
num_heads: 1
num_head_channels: -1
attention_resolutions: "16"
dropout: 0

learn_sigma:     false
class_cond:     false
use_checkpoint: false
use_fp16:       false
use_new_attention_order:  false