autoencoder:
  num_channels:   32
  num_res_blocks: 1

operator:
  operator_dim:   null    # will be set in code:  raw_state_dim + latent_dim

consume:          # how many snapshots to feed the AE
  T: 100          # same as cfm.traj.traj_steps
  B: 2000         # same as cfm.traj.n_traj

train:
  accelerator: gpu
  devices: [0]
  device: cuda

  # TODO: Check those bc batch size doesn't change anything when you train
  max_epochs:     1
  batch_size:     128
  num_workers:    4

  autoencoder_lr: 0.001
  lie_lr:         0.0001
  lr_scheduler:   ReduceLROnPlateau

  gamma:          0.99
  delta_t:        0.01

  decode_predict: true
  vae_loss:       false
  koop_reg:       false
  energy_penalty: false

  multistep:      false
  period:         10
  time_dep:       true
  num_iter:       100
  warmup_step:    10

  fid_interval:   500
  log_every_n_steps:                50
  check_val_every_n_train_steps:   200